### ISSUE TITLE
Demo Instance

### ISSUE THREAD

**Issue by dpaola2** [dpaola2/QueryClips#68]
- [ ] new heroku app @ demo.queryclips.com
- [ ] dummy e-commerce database
- [ ] demo credentials, database connections, and saved queries
- [ ] nightly rake task to reset accounts, DB connections, and queries

**Comment by dpaola2** [comment]
Closing this in light of some future hosted instance plans.
